In [26]:
import numpy as np

In [27]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
arr = np.array(lista)

In [29]:
type(arr)

numpy.ndarray

In [30]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr[0]

1

In [32]:
arr[0] + arr[5]

7

In [33]:
matriz[0, 1]

2

In [34]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [35]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [36]:
arr[::3]

array([1, 4, 7])

In [37]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [38]:
arr[-3:]

array([7, 8, 9])

In [39]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])