# Creando arrays
Numpy nos da varios métodos muy eficientes para poder crear arrays desde 0.

In [ ]:
import numpy as np

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Este método de NumPy nos permite generar arrays sin definir previamente una lista.

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Un tercer argumento permite definir un tamaño de paso.

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

`np.zeros()` Nos permite definir estructuras o esquemas.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

De igual manera, tenemos `np.ones()`

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

np.linspace() Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá.

In [ ]:
np.linspace(0,19,10)

array([ 0.        ,  2.11111111,  4.22222222,  6.33333333,  8.44444444,
       10.55555556, 12.66666667, 14.77777778, 16.88888889, 19.        ])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

También podemos crear una matriz con una diagonal de 1 y el resto de 9.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Otro método importante es generar números aleatorios.

In [ ]:
np.random.rand()

0.18061497097124624

También se pueden generar vectores.

In [ ]:
np.random.rand(4)

array([0.10465244, 0.05602722, 0.37449905, 0.11540181])

Y a su vez generar matrices.

In [ ]:
np.random.rand(4,4)

array([[0.93911093, 0.38399062, 0.25877711, 0.05894148],
       [0.60746664, 0.75209333, 0.96537766, 0.61217955],
       [0.76538573, 0.02891988, 0.80130885, 0.70416878],
       [0.26354842, 0.49423572, 0.29075241, 0.60583983]])

NumPy nos permite también generar números enteros.
En este caso números enteros entre el 1 y 14

In [ ]:
np.random.randint(1,15)

3

También podemos llevarlos a una estructura definida.

In [ ]:
np.random.randint(1,100, (10,10))

array([[80, 74, 21, 97, 68, 94, 53, 19, 76, 36],
       [94, 30, 42, 59, 29, 52, 10, 91, 81, 47],
       [27, 39, 90,  7, 51, 46, 13, 34, 64,  1],
       [ 2, 35, 91, 26, 97, 15, 10, 63, 25, 45],
       [55, 97, 53, 34, 67, 28, 35, 53, 29, 90],
       [26, 25, 79, 23,  2, 26, 26, 51, 39, 68],
       [92,  7, 52, 18, 64,  8, 22, 39, 36, 40],
       [29, 19, 11, 20, 50, 36, 30, 86, 92,  2],
       [77, 33, 43, 12, 13, 93, 10, 60, 95,  5],
       [18, 50, 13, 87, 12, 38, 75, 83, 69, 56]])

### Recursos
[Array creation routines](https://numpy.org/doc/stable/reference/routines.array-creation.html)