# Funciones principales de NumPy
Vamos a ver cuáles son las funciones que se utilizan normalmente con NumPy cuando analizamos los datos.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 20, 10)

In [3]:
matriz = arr.reshape(2,5)
matriz

array([[11,  5,  4,  9, 12],
       [ 4, 12, 18,  7, 15]])

In [4]:
arr

array([11,  5,  4,  9, 12,  4, 12, 18,  7, 15])

In [5]:
matriz

array([[11,  5,  4,  9, 12],
       [ 4, 12, 18,  7, 15]])

.max Para el máximo

In [6]:
arr.max()

18

In [7]:
matriz.max()

18

Podemos regresar los máximos de cada fila o columna especificando el eje

Recuerda que:
- 0 -> Columnas
- 1 -> Filas

In [8]:
matriz.max(0)

array([11, 12, 18,  9, 15])

In [9]:
matriz.max(1)

array([12, 18])

También tenemos .argmax() que nos devuelve la posición del elemento

In [10]:
arr.argmax()

7

En el caso de la matriz nos muestra con un 1 dónde se encuentra el mayor entre las columnas

In [11]:
matriz.argmax(0)

array([0, 1, 1, 0, 1])

De forma análoga tenemos .min()

In [12]:
arr.min()

4

In [13]:
matriz.min()

4

In [14]:
arr.argmin()

2

In [15]:
matriz.argmin(0)

array([1, 0, 0, 1, 0])

In [16]:
matriz.argmin(1)

array([2, 0])

Podemos saber la distancia entre el valor más bajo con el más alto.

In [17]:
arr.ptp()

14

In [18]:
matriz.ptp(0)

array([ 7,  7, 14,  2,  3])

## Análisis estadístico
**ordernar los elementos**

In [19]:
arr

array([11,  5,  4,  9, 12,  4, 12, 18,  7, 15])

In [20]:
arr.sort()

In [21]:
arr

array([ 4,  4,  5,  7,  9, 11, 12, 12, 15, 18])

**Obtener un percentil:**

In [22]:
np.percentile(arr, 50)

10.0

In [23]:
np.percentile(arr, 0)

4.0

In [24]:
np.percentile(arr, 100)

18.0

Mediana:

In [25]:
np.median(arr)

10.0

In [26]:
np.median(matriz, 1)

array([ 5., 12.])

Desviación estándar:

In [27]:
np.std(arr)

4.517742799230607

Varianza:

In [28]:
np.var(arr)

20.410000000000004

Promedio:

In [29]:
np.mean(arr)

9.7

Lo mismo aplica para las matrices.

In [30]:
np.median(matriz, 1)

array([ 5., 12.])

## Concatenación
Se pueden unir dos arrays

In [31]:
a = np.array([[1,2], [3,4]])
b = np.array([5, 6])

In [32]:
# np.concatenate((a,b), axis = 0)
# ---> ValueError: all the input arrays must have same number of dimensions,
# but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 
# dimension(s)

El error anterior es debido a que ‘a’ tiene 2 dimensiones, mientras que ‘b’ tiene 1.

In [33]:
a.ndim

2

In [34]:
b.ndim

1

Debemos poner ‘b’ en 2 dimensiones también.

In [35]:
b = np.expand_dims(b, axis = 0)

In [36]:
b

array([[5, 6]])

In [37]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

De igual manera, podemos agregarlo en el otro eje

In [38]:
# np.concatenate((a,b), axis = 1)

# ValueError: all the input array dimensions for the concatenation axis must 
# match exactly, but along dimension 0, the array at index 0 has size 2 and
# the array at index 1 has size 1


Como ‘b’ es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta.

La transpuesta pone nuestro array en sentido opuesto, si el array original es (1,2), con la transpuesta quedará (2,1)

In [39]:
b.T

array([[5],
       [6]])

In [40]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])