# Copy

`.copy()` nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Tomamos un trozo del array original

In [6]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

Queremos pasar todas nuestras variables a 0

In [8]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.

Con .copy() creamos una copia para no dañar nuestro array original

In [12]:
arr_copy = arr.copy()

In [13]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Esta función te ayudará a prevenir muchos errores y tener más confianza a la hora de manipular los datos

> Siempre que desees sacar un trozo de alguna entidad de numpy (vector, matriz, tensor, etc.) **siempre realiza una copia** de no hacerlo corres el riesgo de sobreescribir información