# Operaciones
Existen diferentes operaciones que se pueden usar para los arrays de NumPy.

In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

Una lista de Python entiende que quieres duplicar los datos. No es lo que buscamos.

Pero Numpy lo entiende mucho mejor

In [6]:
arr = np.arange(0, 10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ahora multiplicamos por un vector:

In [7]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Operación suma de vectores:

In [8]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

División con un vector

Como en este caso la primera posición del array es 0, muestra un error pero, no detiene el proceso

In [11]:
11 / arr

<ipython-input-11-8adcf172d45b>:1: RuntimeWarning: divide by zero encountered in true_divide
  11 / arr


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222])

In [12]:
arr**2 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Sumar dos arrays de igual dimensiones las hace elemento por elemento:

In [13]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Lo mismo aplica para matrices.

In [17]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Una operación importante es la de punto por punto, aquí dos formas de hacerla:

In [19]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [20]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

## Recursos

- [Basic array operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)